### ISSUE TITLE
Could not build project

### ISSUE THREAD

**Issue by northcapen** [angryziber/kotlin-jooby-svelte-template#1]
anton@Antons-MacBook-Pro kotlin-jooby-svelte-template % ./gradlew build
...
> Task :compileKotlin FAILED
e: /Users/anton/IdeaProjects/kotlin-jooby-svelte-template/src/app/AutoCreatingServiceRegistry.kt: (17, 14): Unresolved reference: packageName

FAILURE: Build failed with an exception.

BUILD FAILED in 4s

I've Java 8, MacOS 10.15

**Comment by angryziber** [comment]
Solved quite some time ago :-)
