### ISSUE TITLE
Transaction won't flush on application shutdown

### ISSUE THREAD

**Issue by asm0dey** [angryziber/kotlin-jooby-svelte-template#3]
https://github.com/angryziber/kotlin-jooby-svelte-template/blob/master/src/db/ThreadLocalTransaction.kt#L23

Here we can see ThreadLocal of transactions. At any given moment there can be an arbitrary number of opened connections. On application exit we don't know what will happen to those transactions. Ideally they should be rolled back or commited (and I believe that we have no way to determine if we can commit transaction without breaking consistency). This can lead to unpredictable consequences. Behaviour should be explicitly specified.

**Comment by angryziber** [comment]
On clean exit, all requests should finish before the JVM is terminated, resulting in commit/rollback as normal.

If you mean a JVM crash, then it will depend on the DB server, there is nothing the app can do. E.g. Oracle will commit, Postgre & MySQL would rollback, I believe.

**Comment by asm0dey** [comment]
You're right, here is code for correct shutdown: https://github.com/jooby-project/jooby/blob/2.x/modules/jooby-hikari/src/main/java/io/jooby/hikari/HikariModule.java#L182
