### ISSUE TITLE
Potential JDBC incompatibility

### ISSUE THREAD

**Issue by asm0dey** [angryziber/kotlin-jooby-svelte-template#6]
You're using setObject to set value in PreparedStatement (https://github.com/angryziber/kotlin-jooby-svelte-template/blob/84bccd62ec5e8c889491b0b139765ecd5668d6bf/src/db/JdbcExtensions.kt#L81), but it's not guaranteed to work: https://stackoverflow.com/a/35532530/1160959

**Comment by angryziber** [comment]
Works with all modern JDBC drivers, even Oracle, which often lags behind. I have seen only problems with Date/Timestamp classes with some drivers, basic types usually work well.

Why should I write the ifs/switch if most drivers already have it? Like your example in MySQL

**Comment by asm0dey** [comment]
Well, as of me it's matter of compatibility. We don't know who'll use this application as template so possibly safe setters could be better. Alternative solution I see is to add waning about potential incompatibility with some (old) JDBC drivers.

**Comment by angryziber** [comment]
The point of a template is that you can modify it however you like to suit your needs. Its not a framework :-)
