### ISSUE TITLE
End-to-End tests not pass

### ISSUE THREAD

**Issue by karnilaev** [angryziber/kotlin-jooby-svelte-template#9]
I start End-to-End tests by command `./gradlew e2eTest` and tests fail. There is log
[reports.zip](https://github.com/angryziber/kotlin-jooby-svelte-template/files/6759679/reports.zip).

I tried to investigate it:

- tests fail because javascript is not found
![CleanShot 2021-07-04 at 12 54 46@2x](https://user-images.githubusercontent.com/5828648/124380754-24dd0800-dcc7-11eb-93e3-adab3a69c3b7.png)
- main.js is absent in app.jar 
![CleanShot 2021-07-04 at 12 57 29@2x](https://user-images.githubusercontent.com/5828648/124380796-74233880-dcc7-11eb-865e-ce7e9a688540.png)
- if I try to start e2e tests from IDE and run command `npm run build` before starting tests I get the following error
![CleanShot 2021-07-04 at 13 04 34@2x](https://user-images.githubusercontent.com/5828648/124380957-95d0ef80-dcc8-11eb-9f29-6f5d3138310a.png)
It happens because browser searches file en.json by path http://localhost:18097/_dist_/ui/en.json, but file is in directory i18n
![CleanShot 2021-07-04 at 13 08 58@2x](https://user-images.githubusercontent.com/5828648/124381033-0d068380-dcc9-11eb-8838-472fef25e28e.png)
- and even if I put en.json into directory "ui" then following error occurs
![CleanShot 2021-07-04 at 13 10 50@2x](https://user-images.githubusercontent.com/5828648/124381130-771f2880-dcc9-11eb-984c-0d662c3447e8.png)
- When start application from docker, then main.css and en.json don't exist
![CleanShot 2021-07-04 at 17 52 48@2x](https://user-images.githubusercontent.com/5828648/124389689-e9efca00-dcf0-11eb-871d-0c979f19d93c.png)

I don't know how to fix it, but I will try later

**Comment by karnilaev** [comment]
I found that if turn off option optimize.bundle in snowpack.config.mjs then e2e tests pass.
For me it's acceptable solution. Will you approve such pull request?

**Comment by angryziber** [comment]
@karnilaev thanks, it seems that snowpack's built-in optimization (using esbuild) is not ready yet, maybe will try it later
